apiVersion: v1
appVersion: 0.1.0
description: version propia One of the most versatile open source content management systems.
engine: gotpl
home: http://www.drupal.org/
icon: https://bitnami.com/assets/stacks/drupal/img/drupal-stack-220x234.png
keywords:
- drupal
- cms
- blog
- http
- web
- application
- php
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: drupal
sources:
- https://github.com/bitnami/bitnami-docker-drupal
version: 6.2.21
