{{- if .Values.autoscalling.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "opencart.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "opencart.fullname" . }}
  minReplicas: {{ .Values.autoscalling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscalling.maxReplicas | default 4 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscalling.cpu | default 60 }}
  - type: Pods
    pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: {{ .Values.autoscalling.packets | default 1000 }}
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1beta1
        kind: Ingress
        name: main-route
      target:
        type: Value
        value: {{ .Values.autoscalling.requests | default 3000 }}
{{- end }}
