{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "opencart.fullname" . }}
  labels:
    app: "{{ template "opencart.fullname" . }}"
    chart: "{{ template "opencart.chart" . }}"
    release: {{ .Release.Name | quote }}
  annotations:
    {{- if .Values.ingress.certManager }}
    cert-manager.io/issuer: "letsencrypt-staging"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
  {{- range .Values.ingress.hosts }}
  {{- if .tls }}
  - hosts:
  {{- if .tlsHosts }}
  {{- range $host := .tlsHosts }}
    - {{ $host }}
  {{- end }}
  {{- else }}
    - {{ .name }}
  {{- end }}
    secretName: {{ .tlsSecret }}
  {{- end }}
  {{- end }}

  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - path: {{ default "/" .path }}
        backend:
          serviceName: {{ template "opencart.fullname" $ }}
          servicePort: http
  {{- end }}
{{- end }}
