#los path deben estar creados en todos los nodos Kubernetes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv0
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-bbdd 
#standard
  hostPath:
    path: "/var/pods-pv/mariadb/"	
#node0
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-bbdd
#standard
  hostPath:
    path: "/var/pods-pv/mariadb/"	
#node1
