apiVersion: v1
appVersion: 0.1.0
description: version propia modificada a partir de la version bitnami/opencart 3.0.3-3 
  'A free and open source e-commerce platform for online merchants. It provides a professional and reliable foundation for a successful online store.'
engine: gotpl
home: https://opencart.com/
icon: https://bitnami.com/assets/stacks/opencart/img/opencart-stack-110x117.png
keywords:
- opencart
- e-commerce
- http
- web
- php
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: opencart
sources:
- https://github.com/bitnami/bitnami-docker-opencart
version: 7.0.15
