apiVersion: v1
appVersion: 3.9.18
description: 7.1.17 PHP content management system (CMS) for publishing web content
engine: gotpl
home: http://www.joomla.org/
icon: https://bitnami.com/assets/stacks/joomla/img/joomla-stack-220x234.png
keywords:
- joomla
- cms
- blog
- http
- php
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: joomla
sources:
- https://github.com/bitnami/bitnami-docker-joomla
version: 0.1.0
